# Session 08 — Pandas Foundations and Exploration
## Python Fundamentals & Practical Applications — 48-Hour Edition

**STUDENT EDITION — WRITE YOUR OWN CODE**  
**Duration:** 4 classroom hours (including a 30-minute break)  
**Audience:** complete beginners and learners transferring from spreadsheets or other programming languages

> **Beginner promise:** We build one table step by step, predict results, practise each idea, and finish with a small report using realistic synthetic data.
> **Working habit:** Ask a question first, inspect the data, then write the smallest useful Pandas expression.

In [1]:
student_name = input("Enter your name: ")
print(f"{student_name}, welcome to the Pandas foundations session.")

mo, welcome to the Pandas foundations session.

## Learning outcomes

By the end of this session, you should be able to:

1. Explain the difference between a DataFrame and a Series.
2. Read a CSV file and inspect its shape, columns, types, and first rows.
3. Select columns and filter rows with Boolean conditions.
4. Create a calculated column.
5. Summarise categories with `value_counts()`, `describe()`, and `groupby()`.
6. Save a result as a CSV file.

**Total: 240 minutes.** Challenge work may become homework if the class needs more time.

## Google Colab quick start — ابدأ من هنا

Open the notebook in [Google Colab](https://colab.research.google.com/) or upload it using **File → Upload notebook**. Run the setup cell before the examples.

The course datasets are synthetic and are supplied in the course `datasets` folder.

In [33]:
from pathlib import Path
import sys
import pandas as pd

IS_COLAB = "google.colab" in sys.modules
if IS_COLAB:
    COURSE_ROOT = Path("/content/python_48h_course")
else:
    HERE = Path.cwd()
    print("Current working directory:", HERE)
    # COURSE_ROOT = HERE if (HERE / "datasets").exists() else HERE.parent
    COURSE_ROOT = HERE
    print("Course root directory:", COURSE_ROOT)

DATA_DIR = COURSE_ROOT / "datasets"
OUTPUT_DIR = COURSE_ROOT / "outputs"
DATA_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
print("Dataset folder:", DATA_DIR)
print("Output folder:", OUTPUT_DIR)

Current working directory: d:\CLS_DataScience\CLS_Python\Oct 2026\3rd_edition\Python_48H_Student_Pack\Python_48H_Google_Colab_Edition\student_notebooks
Course root directory: d:\CLS_DataScience\CLS_Python\Oct 2026\3rd_edition\Python_48H_Student_Pack\Python_48H_Google_Colab_Edition\student_notebooks
Dataset folder: d:\CLS_DataScience\CLS_Python\Oct 2026\3rd_edition\Python_48H_Student_Pack\Python_48H_Google_Colab_Edition\student_notebooks\datasets
Output folder: d:\CLS_DataScience\CLS_Python\Oct 2026\3rd_edition\Python_48H_Student_Pack\Python_48H_Google_Colab_Edition\student_notebooks\outputs

## 1. A DataFrame is a programmable table

A **DataFrame** has rows and columns. A single column is usually a **Series**. The labels help us ask for the data we need.

Run the example, then change one value and run it again.

In [29]:
# Create a sample DataFrame
sample = pd.DataFrame({
    "team": ["Ahly", "Zamalek", "Pyramids"],
    "score": [82, 74, 91]
})

sample

       team  score
0      Ahly     82
1   Zamalek     74
2  Pyramids     91

In [30]:
print("Type of sample:", type(sample).__name__)

print("Type of one column:", type(sample["score"]).__name__)

Type of sample: DataFrame
Type of one column: Series

In [34]:
# You can either add a row or change a score like this:

sample.loc[3] = ["PSG", 94]  # Add a new row

sample.loc[1, "score"] = 80  # Change the score for the Green team

sample

       team  score
0      Ahly     82
1   Zamalek     80
2  Pyramids     91
3       PSG     94

### Guided activity 1 — create and inspect a table

Before running the next cell, predict its shape and column names. Then add extra row to `sample` and change one score.

In [32]:
# Get information about the DataFrame Shape and columns

print("Shape:", sample.shape)

print("Columns:", sample.columns.to_list())

print("Scores:")

print(sample["score"])

Shape: (4, 2)
Columns: ['team', 'score']
Scores:
0    82
1    80
2    91
3    88
Name: score, dtype: int64

In [ ]:
# TODO: Add one row to `sample` or change one score.

## 2. Read a CSV and inspect before analysing

The first step with an unfamiliar table is not a chart. It is a quick inspection: size, names, sample rows, data types, and missing values.

`work_items.csv` contains synthetic operational records used throughout this session.

In [6]:
# Read the work_items.csv file into a DataFrame
work = pd.read_csv(DATA_DIR / "work_items.csv")

print("Shape:", work.shape)

print("Columns:", work.columns.to_list())

work.head()

Shape: (128, 9)
Columns: ['case_id', 'sector', 'team', 'priority', 'status', 'hours_open', 'estimated_cost', 'created_date', 'owner']

,case_id,sector,team,priority,status,hours_open,estimated_cost,created_date,owner
0,CASE-0001,Research,Team 2,medium,open,10.2,137.5,2026-01-05,Learner_02
1,CASE-0002,Audit,Team 3,high,in_progress,20.0,175.0,2026-01-05,Learner_03
2,CASE-0003,Software,Team 4,low,closed,29.8,212.5,2026-01-06,Learner_04
3,CASE-0004,Healthcare,Team 1,medium,open,39.5,248.0,2026-01-06,Learner_05
4,CASE-0005,Banking,Team 2,high,in_progress,49.2,285.5,2026-01-06,Learner_06

In [7]:
# Get information about the DataFrame
work.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   case_id         128 non-null    object
 1   sector          128 non-null    object
 2   team            128 non-null    object
 3   priority        128 non-null    object
 4   status          128 non-null    object
 5   hours_open      128 non-null    float64
 6   estimated_cost  128 non-null    float64
 7   created_date    128 non-null    object
 8   owner           128 non-null    object
dtypes: float64(2), object(7)
memory usage: 9.1+ KB

In [8]:
# Get descriptive statistics for the specified columns
work[["hours_open", "estimated_cost"]].describe().round(2)

       hours_open  estimated_cost
count      128.00          128.00
mean        30.31          899.75
std         17.27          457.74
min          0.50          120.50
25%         15.50          506.12
50%         30.15          900.75
75%         44.97         1289.12
max         59.80         1692.50

### Guided activity 2 — inspect a different dataset

Load `energy_readings.csv`. Print its shape, columns, and first three rows. Which column looks numeric? Which column identifies a group such as a site?

In [ ]:
# TODO: load energy_readings.csv and inspect it

          day    site  solar_kwh  temperature_c
0  2026-01-06  Site-2       32.4           18.8
1  2026-01-07  Site-3       39.4           19.6
2  2026-01-08  Site-1       46.4           20.4
3  2026-01-09  Site-2       53.4           21.2
4  2026-01-10  Site-3       60.4           22.0

## 3. Select columns and filter rows

Use brackets to select columns. Use `.loc[rows, columns]` when you want to make the row and column choices explicit. A condition creates a Boolean Series: `True` keeps a row and `False` excludes it.

**When combining conditions, put parentheses around each comparison.**

In [10]:
# Select specific columns
selected = work[["case_id", "sector", "status", "priority"]]

selected.head()

     case_id      sector       status priority
0  CASE-0001    Research         open   medium
1  CASE-0002       Audit  in_progress     high
2  CASE-0003    Software       closed      low
3  CASE-0004  Healthcare         open   medium
4  CASE-0005     Banking  in_progress     high

In [11]:
# Sample 5 rows from the selected DataFrame
selected.sample(5, random_state=42)

      case_id      sector       status priority
55  CASE-0056     Telecom  in_progress     high
40  CASE-0041    Research  in_progress     high
19  CASE-0020  Healthcare  in_progress     high
31  CASE-0032     Telecom  in_progress     high
98  CASE-0099    Software       closed      low

In [27]:
# Filter the DataFrame based on status and priority

is_open = work["status"] == "open"

is_medium = work["priority"] == "medium"

# Create a new DataFrame with open and medium priority cases and select specific columns with copy
open_medium = work.loc[(is_open) & (is_medium), ["case_id", "status", "priority", "sector", "hours_open"]].copy()

# Display the first 5 rows of the new DataFrame
open_medium.head()

      case_id status priority      sector  hours_open
0   CASE-0001   open   medium    Research        10.2
3   CASE-0004   open   medium  Healthcare        39.5
6   CASE-0007   open   medium          HR         8.8
9   CASE-0010   open   medium       Audit        38.0
12  CASE-0013   open   medium     Banking         7.2

In [36]:
# Filter the work DataFrame to keep only cases that are:
# - currently open
# - assigned medium priority using the query method and select specific columns with copy

open_medium = (
    work.query("status == 'open' and priority == 'medium'")
    # Select only the columns needed for this analysis
    .loc[:, ["case_id", "status", "priority", "sector", "hours_open"]]
    # Create an independent copy so later changes do not modify the original DataFrame
    .copy()
)

# Show the first 5 filtered cases for a quick check
open_medium.head()

      case_id status priority      sector  hours_open
0   CASE-0001   open   medium    Research        10.2
3   CASE-0004   open   medium  Healthcare        39.5
6   CASE-0007   open   medium          HR         8.8
9   CASE-0010   open   medium       Audit        38.0
12  CASE-0013   open   medium     Banking         7.2

- Use `.copy()` if you plan to modify `open_medium` afterward. It creates an **independent DataFrame**, so changes do not affect the original work DataFrame.

In [13]:
# Get the number of rows in the new DataFrame
open_medium.shape[0]

43

In [14]:
# Get the number of rows in the new DataFrame / 2nd method
len(open_medium)

43

### Guided activity 3 — build a filter in stages

Filter `work` to records from one sector. First inspect `work["sector"].value_counts()`, then create a condition, then print the matching case IDs.

In [24]:
work["sector"].value_counts()

Research            16
Audit               16
Software            16
Healthcare          16
Banking             16
Renewable Energy    16
HR                  16
Telecom             16
Name: sector, dtype: int64

In [ ]:
# TODO: choose a sector, filter the rows, and print case_id

## 4. Add columns and answer summary questions

A calculated column turns a raw field into a useful measure. Pandas applies the operation to the whole column.

`value_counts()` answers “how many?” for categories. `groupby()` answers “how does this measure differ between groups?”

In [16]:
# Add a new column to the DataFrame that calculates the age of each case in days
work["age_days"] = work["hours_open"] / 24

# Display the first 5 rows of the DataFrame with the new column
work[["case_id", "hours_open", "age_days"]].head()

     case_id  hours_open  age_days
0  CASE-0001        10.2  0.425000
1  CASE-0002        20.0  0.833333
2  CASE-0003        29.8  1.241667
3  CASE-0004        39.5  1.645833
4  CASE-0005        49.2  2.050000

In [17]:
print("Status counts:")

work["status"].value_counts()

Status counts:

open           43
in_progress    43
closed         42
Name: status, dtype: int64

In [18]:
# Summary of cases by sector
sector_summary = (
    work.groupby("sector")
        .agg(cases=("case_id", "count"), average_hours=("hours_open", "mean"))
        .sort_values(["cases", "average_hours"], ascending=False)
)

sector_summary.round(2)

                  cases  average_hours
sector
Software             16          33.55
Renewable Energy     16          32.75
Healthcare           16          32.00
Audit                16          31.25
Telecom              16          29.75
Research             16          28.95
HR                   16          27.55
Banking              16          26.70

### Guided activity 4 — compare groups

Create a summary by `priority` with the number of cases and average estimated cost. Sort it from largest average cost to smallest.

In [ ]:
# TODO: use groupby().agg() and sort_values()

## Practice tasks

Complete the guided activities first. Then work independently. Explain what each result means in plain English, not only what code produced it.

### Applied task A — `S08-E01`
Load `transactions_synthetic.csv`. Print its shape, column names, and the five most common transaction types.

In [20]:
# TODO:

### Applied task B — `S08-E02`
Using `work_items.csv`, select high-priority records and print their case IDs and estimated costs.

In [21]:
# TODO:

### Challenge — `S08-E03`
Create a summary by both `sector` and `priority`, with case count and average `hours_open`. Sort by case count descending.

In [22]:
# TODO:

## Guided mini-project — Sector performance snapshot

Create a readable CSV report from `work_items.csv`. Your report must contain one row per sector and:

- case count
- median `hours_open`
- average `estimated_cost`

Save it as `session_08_sector_snapshot.csv` in `OUTPUT_DIR`. Write one sentence explaining an observation from your report.

In [23]:
# TODO: group, aggregate, sort, and export the report

## Exit check — answer from memory

1. What is a DataFrame?
2. What does `.shape` tell you?
3. How do you select several columns?
4. Why do combined conditions need parentheses?
5. What question does `groupby()` help answer?
6. Why would you save a summary to a CSV?

## Common mistakes and next steps

- Inspect the column names before typing them.
- Use `==` for comparison and `=` for assignment.
- Use `.loc` and parentheses when combining filters.
- Do not assume the first five rows represent the whole dataset.
- Explain a grouped result in words.

**Next session:** we will clean imperfect data, handle missing values, convert dates, combine tables, and build a report.